#!/usr/bin/env bash
# Controller, TEB, and command-mux configuration.

FRONTIER_LOG=${FRONTIER_LOG:-${CFG_FRONTIER_LOG:-true}}
LSTE_CONTROLLER=${LSTE_CONTROLLER:-${CFG_LSTE_CONTROLLER:-teb}}

# SA-PPO is retained for reproducible comparison runs, but TEB is the normal
# controller. Keep the legacy parameters isolated from the navigation config.
SAPPO_SPEED=${SAPPO_SPEED:-${CFG_SAPPO_SPEED:-0.50}}
SAPPO_PYTHON=${SAPPO_PYTHON:-${CFG_SAPPO_PYTHON:-$HOME/miniconda3/envs/rlenvs/bin/python}}
SAPPO_CONTROLLER_MODE=${SAPPO_CONTROLLER_MODE:-${CFG_SAPPO_CONTROLLER_MODE:-rl_grid_guard}}
SAPPO_IN_PLACE_TURN_ANGULAR_THRESHOLD=${SAPPO_IN_PLACE_TURN_ANGULAR_THRESHOLD:-${CFG_SAPPO_IN_PLACE_TURN_ANGULAR_THRESHOLD:-0.12}}
SAPPO_BOUNDARY_TURN_LOCK_TIME=${SAPPO_BOUNDARY_TURN_LOCK_TIME:-${CFG_SAPPO_BOUNDARY_TURN_LOCK_TIME:-3.0}}
SAPPO_BOUNDARY_TURN_MAX_DURATION=${SAPPO_BOUNDARY_TURN_MAX_DURATION:-${CFG_SAPPO_BOUNDARY_TURN_MAX_DURATION:-2.8}}
SAPPO_BOUNDARY_TURN_MAX_ANGLE_DEG=${SAPPO_BOUNDARY_TURN_MAX_ANGLE_DEG:-${CFG_SAPPO_BOUNDARY_TURN_MAX_ANGLE_DEG:-112.0}}
SAPPO_BOUNDARY_TURN_MAX_ATTEMPTS=${SAPPO_BOUNDARY_TURN_MAX_ATTEMPTS:-${CFG_SAPPO_BOUNDARY_TURN_MAX_ATTEMPTS:-2}}
SAPPO_BOUNDARY_REENTRY_COOLDOWN=${SAPPO_BOUNDARY_REENTRY_COOLDOWN:-${CFG_SAPPO_BOUNDARY_REENTRY_COOLDOWN:-1.5}}
SAPPO_BOUNDARY_PROGRESS_TIMEOUT=${SAPPO_BOUNDARY_PROGRESS_TIMEOUT:-${CFG_SAPPO_BOUNDARY_PROGRESS_TIMEOUT:-10.0}}
SAPPO_BOUNDARY_PROGRESS_MARGIN=${SAPPO_BOUNDARY_PROGRESS_MARGIN:-${CFG_SAPPO_BOUNDARY_PROGRESS_MARGIN:-0.45}}
SAPPO_BOUNDARY_WALL_DISTANCE=${SAPPO_BOUNDARY_WALL_DISTANCE:-${CFG_SAPPO_BOUNDARY_WALL_DISTANCE:-0.72}}
SAPPO_BOUNDARY_WALL_KP=${SAPPO_BOUNDARY_WALL_KP:-${CFG_SAPPO_BOUNDARY_WALL_KP:-0.45}}
SAPPO_BOUNDARY_WALL_HEADING_KP=${SAPPO_BOUNDARY_WALL_HEADING_KP:-${CFG_SAPPO_BOUNDARY_WALL_HEADING_KP:-0.35}}
SAPPO_BOUNDARY_WALL_MAX_LINEAR=${SAPPO_BOUNDARY_WALL_MAX_LINEAR:-${CFG_SAPPO_BOUNDARY_WALL_MAX_LINEAR:-0.28}}
SAPPO_BOUNDARY_WALL_MAX_RANGE=${SAPPO_BOUNDARY_WALL_MAX_RANGE:-${CFG_SAPPO_BOUNDARY_WALL_MAX_RANGE:-1.80}}
SAPPO_BOUNDARY_WALL_FILTER_ALPHA=${SAPPO_BOUNDARY_WALL_FILTER_ALPHA:-${CFG_SAPPO_BOUNDARY_WALL_FILTER_ALPHA:-0.28}}
SAPPO_BOUNDARY_WALL_ANGULAR_STEP=${SAPPO_BOUNDARY_WALL_ANGULAR_STEP:-${CFG_SAPPO_BOUNDARY_WALL_ANGULAR_STEP:-0.08}}
SAPPO_BOUNDARY_WALL_ANGULAR_DEADBAND=${SAPPO_BOUNDARY_WALL_ANGULAR_DEADBAND:-${CFG_SAPPO_BOUNDARY_WALL_ANGULAR_DEADBAND:-0.035}}
SAPPO_BOUNDARY_GOAL_CANCEL_ANGLE_DEG=${SAPPO_BOUNDARY_GOAL_CANCEL_ANGLE_DEG:-${CFG_SAPPO_BOUNDARY_GOAL_CANCEL_ANGLE_DEG:-165.0}}
SAPPO_BOUNDARY_GOAL_CANCEL_DISTANCE=${SAPPO_BOUNDARY_GOAL_CANCEL_DISTANCE:-${CFG_SAPPO_BOUNDARY_GOAL_CANCEL_DISTANCE:-0.75}}
SAPPO_WAYPOINT_HOLD_RADIUS=${SAPPO_WAYPOINT_HOLD_RADIUS:-${CFG_SAPPO_WAYPOINT_HOLD_RADIUS:-0.40}}
SAPPO_WAYPOINT_SWITCH_DISTANCE=${SAPPO_WAYPOINT_SWITCH_DISTANCE:-${CFG_SAPPO_WAYPOINT_SWITCH_DISTANCE:-0.75}}
SAPPO_GRID_OBSTACLE_RADIUS=${SAPPO_GRID_OBSTACLE_RADIUS:-${CFG_SAPPO_GRID_OBSTACLE_RADIUS:-0.48}}
SAPPO_GRID_EDGE_CLEARANCE=${SAPPO_GRID_EDGE_CLEARANCE:-${CFG_SAPPO_GRID_EDGE_CLEARANCE:-0.42}}
SAPPO_REORIENT_OBSTACLE_CLEARANCE=${SAPPO_REORIENT_OBSTACLE_CLEARANCE:-${CFG_SAPPO_REORIENT_OBSTACLE_CLEARANCE:-0.72}}
SAPPO_GOAL_TOLERANCE=${SAPPO_GOAL_TOLERANCE:-${CFG_SAPPO_GOAL_TOLERANCE:-0.30}}
SAPPO_INTERMEDIATE_GOAL_TOLERANCE=${SAPPO_INTERMEDIATE_GOAL_TOLERANCE:-${CFG_SAPPO_INTERMEDIATE_GOAL_TOLERANCE:-0.45}}
SAPPO_MAX_LINEAR_ACTION_STEP=${SAPPO_MAX_LINEAR_ACTION_STEP:-${CFG_SAPPO_MAX_LINEAR_ACTION_STEP:-0.12}}
SAPPO_MAX_LINEAR_ACTION_DECEL=${SAPPO_MAX_LINEAR_ACTION_DECEL:-${CFG_SAPPO_MAX_LINEAR_ACTION_DECEL:-0.06}}
SAPPO_MAX_ANGULAR_ACTION_STEP=${SAPPO_MAX_ANGULAR_ACTION_STEP:-${CFG_SAPPO_MAX_ANGULAR_ACTION_STEP:-0.16}}
SAPPO_ANGULAR_SIGN_SWITCH_THRESHOLD=${SAPPO_ANGULAR_SIGN_SWITCH_THRESHOLD:-${CFG_SAPPO_ANGULAR_SIGN_SWITCH_THRESHOLD:-0.18}}
SAPPO_BACKGROUND_ENABLED=${SAPPO_BACKGROUND_ENABLED:-${CFG_SAPPO_BACKGROUND_ENABLED:-false}}

TEB_MAX_LINEAR_SPEED=${TEB_MAX_LINEAR_SPEED:-${CFG_TEB_MAX_LINEAR_SPEED:-0.50}}
TEB_EXECUTION_ARCHITECTURE=${TEB_EXECUTION_ARCHITECTURE:-${CFG_TEB_EXECUTION_ARCHITECTURE:-endpoint_action}}
TEB_PERSISTENT_CORRIDOR_RADIUS=${TEB_PERSISTENT_CORRIDOR_RADIUS:-${CFG_TEB_PERSISTENT_CORRIDOR_RADIUS:-0.25}}
TEB_PERSISTENT_FRONTIER_LOOKAHEAD_HANDOFF_ENABLED=${TEB_PERSISTENT_FRONTIER_LOOKAHEAD_HANDOFF_ENABLED:-${CFG_TEB_PERSISTENT_FRONTIER_LOOKAHEAD_HANDOFF_ENABLED:-false}}
TEB_PERSISTENT_FRONTIER_LOOKAHEAD_TRIGGER_DISTANCE=${TEB_PERSISTENT_FRONTIER_LOOKAHEAD_TRIGGER_DISTANCE:-${CFG_TEB_PERSISTENT_FRONTIER_LOOKAHEAD_TRIGGER_DISTANCE:-1.0}}
TEB_PERSISTENT_FRONTIER_ADMISSION_HORIZON=${TEB_PERSISTENT_FRONTIER_ADMISSION_HORIZON:-${CFG_TEB_PERSISTENT_FRONTIER_ADMISSION_HORIZON:-2.0}}
TEB_PERSISTENT_FRONTIER_ADMISSION_MAX_COSTMAP_AGE=${TEB_PERSISTENT_FRONTIER_ADMISSION_MAX_COSTMAP_AGE:-${CFG_TEB_PERSISTENT_FRONTIER_ADMISSION_MAX_COSTMAP_AGE:-0.50}}
TEB_PERSISTENT_FRONTIER_ADMISSION_BLOCKED_COST=${TEB_PERSISTENT_FRONTIER_ADMISSION_BLOCKED_COST:-${CFG_TEB_PERSISTENT_FRONTIER_ADMISSION_BLOCKED_COST:-100}}
TEB_PERSISTENT_FRONTIER_ADMISSION_SERVICE_TIMEOUT=${TEB_PERSISTENT_FRONTIER_ADMISSION_SERVICE_TIMEOUT:-${CFG_TEB_PERSISTENT_FRONTIER_ADMISSION_SERVICE_TIMEOUT:-0.10}}
TEB_PERSISTENT_FRONTIER_ADMISSION_ENDPOINT_EPSILON=${TEB_PERSISTENT_FRONTIER_ADMISSION_ENDPOINT_EPSILON:-${CFG_TEB_PERSISTENT_FRONTIER_ADMISSION_ENDPOINT_EPSILON:-0.20}}
TEB_PERSISTENT_FRONTIER_CURVE_HANDOFF_MAX_HEADING_DEG=${TEB_PERSISTENT_FRONTIER_CURVE_HANDOFF_MAX_HEADING_DEG:-${CFG_TEB_PERSISTENT_FRONTIER_CURVE_HANDOFF_MAX_HEADING_DEG:-65.0}}
TEB_HOMOTOPY_CLASS_PLANNING=${TEB_HOMOTOPY_CLASS_PLANNING:-${CFG_TEB_HOMOTOPY_CLASS_PLANNING:-false}}
# Raw local costmap is the production representation. Set
# TEB_COSTMAP_CONVERTER_PLUGIN explicitly to DBSMCCH for the converter A/B.
TEB_COSTMAP_CONVERTER_PLUGIN=${TEB_COSTMAP_CONVERTER_PLUGIN-${CFG_TEB_COSTMAP_CONVERTER_PLUGIN-disabled}}
TEB_COSTMAP_CONVERTER_SPIN_THREAD=${TEB_COSTMAP_CONVERTER_SPIN_THREAD:-${CFG_TEB_COSTMAP_CONVERTER_SPIN_THREAD:-false}}
TEB_COSTMAP_CONVERTER_RATE=${TEB_COSTMAP_CONVERTER_RATE:-${CFG_TEB_COSTMAP_CONVERTER_RATE:-5}}
TEB_FORWARD_ONLY=${TEB_FORWARD_ONLY:-${CFG_TEB_FORWARD_ONLY:-true}}
TEB_ANGULAR_SIGN_SWITCH_THRESHOLD=${TEB_ANGULAR_SIGN_SWITCH_THRESHOLD:-${CFG_TEB_ANGULAR_SIGN_SWITCH_THRESHOLD:-0.12}}
MUX_GOVERNOR_DECEL=${MUX_GOVERNOR_DECEL:-${CFG_MUX_GOVERNOR_DECEL:-0.60}}
MUX_GOVERNOR_MIN_GAP=${MUX_GOVERNOR_MIN_GAP:-${CFG_MUX_GOVERNOR_MIN_GAP:-0.45}}
MUX_GOVERNOR_MAX_SPEED=${MUX_GOVERNOR_MAX_SPEED:-${CFG_MUX_GOVERNOR_MAX_SPEED:-0.50}}
TEB_ANGULAR_DEADBAND=${TEB_ANGULAR_DEADBAND:-${CFG_TEB_ANGULAR_DEADBAND:-0.02}}
TEB_ACTION_HANDOFF_DISTANCE=${TEB_ACTION_HANDOFF_DISTANCE:-${CFG_TEB_ACTION_HANDOFF_DISTANCE:-1.00}}
TEB_ACTION_HANDOFF_RADIUS=${TEB_ACTION_HANDOFF_RADIUS:-${CFG_TEB_ACTION_HANDOFF_RADIUS:-0.30}}
TEB_ACTION_PROGRESS_TIMEOUT=${TEB_ACTION_PROGRESS_TIMEOUT:-${CFG_TEB_ACTION_PROGRESS_TIMEOUT:-12.0}}
TEB_ACTION_PROGRESS_EPSILON=${TEB_ACTION_PROGRESS_EPSILON:-${CFG_TEB_ACTION_PROGRESS_EPSILON:-0.12}}
TEB_ACTION_HANDOFF_MIN_INTERVAL=${TEB_ACTION_HANDOFF_MIN_INTERVAL:-${CFG_TEB_ACTION_HANDOFF_MIN_INTERVAL:-4.0}}
TEB_FRONTIER_OBSERVATION_COMPLETION_RADIUS=${TEB_FRONTIER_OBSERVATION_COMPLETION_RADIUS:-${CFG_TEB_FRONTIER_OBSERVATION_COMPLETION_RADIUS:-0.0}}
TEB_FRONTIER_OBSERVATION_COMPLETION_MAX_LINEAR_SPEED=${TEB_FRONTIER_OBSERVATION_COMPLETION_MAX_LINEAR_SPEED:-${CFG_TEB_FRONTIER_OBSERVATION_COMPLETION_MAX_LINEAR_SPEED:-0.15}}
TEB_FRONTIER_OBSERVATION_STATIONARY_HOLD=${TEB_FRONTIER_OBSERVATION_STATIONARY_HOLD:-${CFG_TEB_FRONTIER_OBSERVATION_STATIONARY_HOLD:-0.10}}
TEB_FRONTIER_CONTINUOUS_PREFETCH_HANDOFF_ENABLED=${TEB_FRONTIER_CONTINUOUS_PREFETCH_HANDOFF_ENABLED:-${CFG_TEB_FRONTIER_CONTINUOUS_PREFETCH_HANDOFF_ENABLED:-false}}
TEB_FRONTIER_CONTINUOUS_PREFETCH_HANDOFF_TIMEOUT=${TEB_FRONTIER_CONTINUOUS_PREFETCH_HANDOFF_TIMEOUT:-${CFG_TEB_FRONTIER_CONTINUOUS_PREFETCH_HANDOFF_TIMEOUT:-1.50}}
TEB_NATIVE_REORIENTATION_ENABLED=${TEB_NATIVE_REORIENTATION_ENABLED:-${CFG_TEB_NATIVE_REORIENTATION_ENABLED:-true}}
TEB_NATIVE_REORIENTATION_LINEAR_THRESHOLD=${TEB_NATIVE_REORIENTATION_LINEAR_THRESHOLD:-${CFG_TEB_NATIVE_REORIENTATION_LINEAR_THRESHOLD:-0.03}}
TEB_NATIVE_REORIENTATION_ANGULAR_THRESHOLD=${TEB_NATIVE_REORIENTATION_ANGULAR_THRESHOLD:-${CFG_TEB_NATIVE_REORIENTATION_ANGULAR_THRESHOLD:-0.15}}
TEB_NATIVE_REORIENTATION_YAW_PROGRESS=${TEB_NATIVE_REORIENTATION_YAW_PROGRESS:-${CFG_TEB_NATIVE_REORIENTATION_YAW_PROGRESS:-0.10}}
TEB_NATIVE_REORIENTATION_STAGNATION_TIMEOUT=${TEB_NATIVE_REORIENTATION_STAGNATION_TIMEOUT:-${CFG_TEB_NATIVE_REORIENTATION_STAGNATION_TIMEOUT:-1.50}}
TEB_NATIVE_REORIENTATION_MAX_EXTENSION=${TEB_NATIVE_REORIENTATION_MAX_EXTENSION:-${CFG_TEB_NATIVE_REORIENTATION_MAX_EXTENSION:-8.0}}
TEB_NATIVE_REORIENTATION_FEEDBACK_TIMEOUT=${TEB_NATIVE_REORIENTATION_FEEDBACK_TIMEOUT:-${CFG_TEB_NATIVE_REORIENTATION_FEEDBACK_TIMEOUT:-0.50}}
TEB_FRONTIER_PRE_ROUTE_ALIGNMENT=${TEB_FRONTIER_PRE_ROUTE_ALIGNMENT:-${CFG_TEB_FRONTIER_PRE_ROUTE_ALIGNMENT:-false}}
TEB_NAVFN_ALLOW_UNKNOWN=${TEB_NAVFN_ALLOW_UNKNOWN:-${CFG_TEB_NAVFN_ALLOW_UNKNOWN:-true}}
TEB_TARGET_EARLY_HANDOFF_DISTANCE=${TEB_TARGET_EARLY_HANDOFF_DISTANCE:-${CFG_TEB_TARGET_EARLY_HANDOFF_DISTANCE:-0.70}}
TEB_TARGET_EARLY_HANDOFF_MIN_DELTA=${TEB_TARGET_EARLY_HANDOFF_MIN_DELTA:-${CFG_TEB_TARGET_EARLY_HANDOFF_MIN_DELTA:-0.40}}
TARGET_CONTINUOUS_HANDOFF_ENABLED=${TARGET_CONTINUOUS_HANDOFF_ENABLED:-${CFG_TARGET_CONTINUOUS_HANDOFF_ENABLED:-true}}
TARGET_CONTINUOUS_HANDOFF_DISTANCE=${TARGET_CONTINUOUS_HANDOFF_DISTANCE:-${CFG_TARGET_CONTINUOUS_HANDOFF_DISTANCE:-0.95}}
TARGET_CONTINUOUS_HANDOFF_MIN_NEW_FRAMES=${TARGET_CONTINUOUS_HANDOFF_MIN_NEW_FRAMES:-${CFG_TARGET_CONTINUOUS_HANDOFF_MIN_NEW_FRAMES:-2}}
TEB_FRONTIER_REPLACEMENT_MAX_DELTA=${TEB_FRONTIER_REPLACEMENT_MAX_DELTA:-${CFG_TEB_FRONTIER_REPLACEMENT_MAX_DELTA:-1.00}}
TEB_ALLOW_ROUTE_CONTINUATION_REPLACEMENT=${TEB_ALLOW_ROUTE_CONTINUATION_REPLACEMENT:-${CFG_TEB_ALLOW_ROUTE_CONTINUATION_REPLACEMENT:-true}}
TEB_FRONTIER_EARLY_HANDOFF_MAX_HEADING_DEG=${TEB_FRONTIER_EARLY_HANDOFF_MAX_HEADING_DEG:-${CFG_TEB_FRONTIER_EARLY_HANDOFF_MAX_HEADING_DEG:-45.0}}
TEB_FRONTIER_STALE_RECOVERY_GRACE=${TEB_FRONTIER_STALE_RECOVERY_GRACE:-${CFG_TEB_FRONTIER_STALE_RECOVERY_GRACE:-4.0}}
TEB_FRONTIER_STALE_RECOVERY_MAX_DISTANCE=${TEB_FRONTIER_STALE_RECOVERY_MAX_DISTANCE:-${CFG_TEB_FRONTIER_STALE_RECOVERY_MAX_DISTANCE:-1.50}}

case "$TEB_EXECUTION_ARCHITECTURE" in
  endpoint_action)
    TEB_PERSISTENT_EXECUTION=false
    TEB_BASE_GLOBAL_PLANNER=navfn/NavfnROS
    TEB_BASE_LOCAL_PLANNER=teb_local_planner/TebLocalPlannerROS
    TEB_PLANNER_FREQUENCY=0.0
    ;;
  persistent_stream)
    TEB_PERSISTENT_EXECUTION=true
    TEB_BASE_GLOBAL_PLANNER=lste_topo_access/StreamingNavfnPlanner
    TEB_BASE_LOCAL_PLANNER=lste_topo_access/PersistentTebLocalPlanner
    TEB_PLANNER_FREQUENCY=20.0
    ;;
  *)
    echo "[error] TEB_EXECUTION_ARCHITECTURE must be endpoint_action or persistent_stream (got '$TEB_EXECUTION_ARCHITECTURE')" >&2
    exit 1
    ;;
esac

case "$LSTE_CONTROLLER" in
  teleop|sappo|teb) ;;
  *)
    echo "[error] LSTE_CONTROLLER must be 'teleop', 'sappo', or 'teb' (got '$LSTE_CONTROLLER')" >&2
    exit 1
    ;;
esac
