#!/usr/bin/env bash
# Detector backend selection, display behavior, and detection-evaluation data.

DINO_MIN_INTERVAL=${DINO_MIN_INTERVAL:-${CFG_DINO_MIN_INTERVAL:-1.5}}
DINO_INTERVAL_PASS=${DINO_INTERVAL_PASS:-${CFG_DINO_INTERVAL_PASS:-1.5}}
DINO_INTERVAL_SUSPICIOUS=${DINO_INTERVAL_SUSPICIOUS:-${CFG_DINO_INTERVAL_SUSPICIOUS:-1.5}}
DINO_INTERVAL_LOCKED=${DINO_INTERVAL_LOCKED:-${CFG_DINO_INTERVAL_LOCKED:-1.5}}
DINO_INTERVAL_EXHAUSTED=${DINO_INTERVAL_EXHAUSTED:-${CFG_DINO_INTERVAL_EXHAUSTED:-3.0}}
DETECTOR=${DETECTOR:-${CFG_DETECTOR:-wedetect-large}}
DETECTION_TRACKING_MODE=${DETECTION_TRACKING_MODE:-${CFG_DETECTION_TRACKING_MODE:-auto}}
DETECTION_VISUAL_TRACKING_ENABLED=${DETECTION_VISUAL_TRACKING_ENABLED:-${CFG_DETECTION_VISUAL_TRACKING_ENABLED:-true}}
DETECTION_DISPLAY_SYNC_MODE=${DETECTION_DISPLAY_SYNC_MODE:-${CFG_DETECTION_DISPLAY_SYNC_MODE:-latest_frame}}
DETECTION_DISPLAY_HISTORY_SIZE=${DETECTION_DISPLAY_HISTORY_SIZE:-${CFG_DETECTION_DISPLAY_HISTORY_SIZE:-90}}

WDETECT_SOURCE_DIR=${WDETECT_SOURCE_DIR:-$(_resolve "${CFG_WDETECT_SOURCE_DIR:-model/WeDetect}")}
WDETECT_VARIANT=${WDETECT_VARIANT:-${CFG_WDETECT_VARIANT:-base}}
WDETECT_CHECKPOINT=${WDETECT_CHECKPOINT:-$(_resolve "${CFG_WDETECT_CHECKPOINT:-model/WeDetect/checkpoints/wedetect_base.pth}")}
WDETECT_LANGUAGE_MODEL=${WDETECT_LANGUAGE_MODEL:-$(_resolve "${CFG_WDETECT_LANGUAGE_MODEL:-model/WeDetect/xlm-roberta-base}")}
WDETECT_SCORE_THRESHOLD=${WDETECT_SCORE_THRESHOLD:-${CFG_WDETECT_SCORE_THRESHOLD:-0.20}}
WDETECT_NMS_IOU=${WDETECT_NMS_IOU:-${CFG_WDETECT_NMS_IOU:-0.70}}
WDETECT_PRE_NMS_TOPK=${WDETECT_PRE_NMS_TOPK:-${CFG_WDETECT_PRE_NMS_TOPK:-3000}}
WDETECT_MAX_DETECTIONS=${WDETECT_MAX_DETECTIONS:-${CFG_WDETECT_MAX_DETECTIONS:-100}}
WDETECT_USE_FP16=${WDETECT_USE_FP16:-${CFG_WDETECT_USE_FP16:-true}}
WDETECT_RUNTIME=${WDETECT_RUNTIME:-${CFG_WDETECT_RUNTIME:-tensorrt}}
WDETECT_VISION_ONNX=${WDETECT_VISION_ONNX:-$(_resolve "${CFG_WDETECT_VISION_ONNX:-model/WeDetect/deploy/onnx_models/wedetect_base_vision.onnx}")}
WDETECT_TRT_ENGINE_CACHE=${WDETECT_TRT_ENGINE_CACHE:-$(_resolve "${CFG_WDETECT_TRT_ENGINE_CACHE:-model/WeDetect/deploy/trt_cache}")}
WDETECT_TRT_MAX_CLASSES=${WDETECT_TRT_MAX_CLASSES:-${CFG_WDETECT_TRT_MAX_CLASSES:-16}}
WDETECT_SPIN_HZ=${WDETECT_SPIN_HZ:-${CFG_WDETECT_SPIN_HZ:-10.0}}
WDETECT_MIN_INTERVAL=${WDETECT_MIN_INTERVAL:-${CFG_WDETECT_MIN_INTERVAL:-0.10}}
WDETECT_INTERVAL_PASS=${WDETECT_INTERVAL_PASS:-${CFG_WDETECT_INTERVAL_PASS:-0.10}}
WDETECT_INTERVAL_SUSPICIOUS=${WDETECT_INTERVAL_SUSPICIOUS:-${CFG_WDETECT_INTERVAL_SUSPICIOUS:-0.10}}
WDETECT_INTERVAL_LOCKED=${WDETECT_INTERVAL_LOCKED:-${CFG_WDETECT_INTERVAL_LOCKED:-0.10}}
WDETECT_INTERVAL_EXHAUSTED=${WDETECT_INTERVAL_EXHAUSTED:-${CFG_WDETECT_INTERVAL_EXHAUSTED:-0.30}}
WDETECT_SMALL_OBJECT_TILE_SEARCH_ENABLED=${WDETECT_SMALL_OBJECT_TILE_SEARCH_ENABLED:-${CFG_WDETECT_SMALL_OBJECT_TILE_SEARCH_ENABLED:-true}}
WDETECT_SMALL_OBJECT_TILE_LAYOUT=${WDETECT_SMALL_OBJECT_TILE_LAYOUT:-${CFG_WDETECT_SMALL_OBJECT_TILE_LAYOUT:-uniform_grid}}
WDETECT_SMALL_OBJECT_TILE_GRID=${WDETECT_SMALL_OBJECT_TILE_GRID:-${CFG_WDETECT_SMALL_OBJECT_TILE_GRID:-2}}
WDETECT_SMALL_OBJECT_TILE_OVERLAP=${WDETECT_SMALL_OBJECT_TILE_OVERLAP:-${CFG_WDETECT_SMALL_OBJECT_TILE_OVERLAP:-0.20}}
WDETECT_SMALL_OBJECT_CENTER_BAND_HEIGHT_RATIO=${WDETECT_SMALL_OBJECT_CENTER_BAND_HEIGHT_RATIO:-${CFG_WDETECT_SMALL_OBJECT_CENTER_BAND_HEIGHT_RATIO:-0.72}}
WDETECT_SMALL_OBJECT_CENTER_BAND_CROPS=${WDETECT_SMALL_OBJECT_CENTER_BAND_CROPS:-${CFG_WDETECT_SMALL_OBJECT_CENTER_BAND_CROPS:-4}}
WDETECT_SMALL_OBJECT_TILE_INTERVAL=${WDETECT_SMALL_OBJECT_TILE_INTERVAL:-${CFG_WDETECT_SMALL_OBJECT_TILE_INTERVAL:-2.0}}

TARGET_EVAL_ENABLED=${TARGET_EVAL_ENABLED:-${CFG_TARGET_EVAL_ENABLED:-false}}
TARGET_EVAL_GAZEBO_TARGET_MODEL=${TARGET_EVAL_GAZEBO_TARGET_MODEL:-${CFG_TARGET_EVAL_GAZEBO_TARGET_MODEL:-}}
TARGET_EVAL_GAZEBO_ROBOT_MODEL=${TARGET_EVAL_GAZEBO_ROBOT_MODEL:-${CFG_TARGET_EVAL_GAZEBO_ROBOT_MODEL:-pro3}}
TARGET_EVAL_WORLD_FRAME=${TARGET_EVAL_WORLD_FRAME:-${CFG_TARGET_EVAL_WORLD_FRAME:-world}}
TARGET_EVAL_ODOM_FRAME=${TARGET_EVAL_ODOM_FRAME:-${CFG_TARGET_EVAL_ODOM_FRAME:-odom}}
TARGET_EVAL_CAMERA_FRAME=${TARGET_EVAL_CAMERA_FRAME:-${CFG_TARGET_EVAL_CAMERA_FRAME:-kinect_rgb_optical_frame}}
TARGET_EVAL_CAMERA_INFO_TOPIC=${TARGET_EVAL_CAMERA_INFO_TOPIC:-${CFG_TARGET_EVAL_CAMERA_INFO_TOPIC:-/kinect/hd/camera_info}}
TARGET_EVAL_DEPTH_ENABLED=${TARGET_EVAL_DEPTH_ENABLED:-${CFG_TARGET_EVAL_DEPTH_ENABLED:-true}}
TARGET_EVAL_DEPTH_TOPIC=${TARGET_EVAL_DEPTH_TOPIC:-${CFG_TARGET_EVAL_DEPTH_TOPIC:-/kinect/hd/image_color_rect/compressedDepth}}
TARGET_EVAL_DEPTH_MAX_SOURCE_AGE_S=${TARGET_EVAL_DEPTH_MAX_SOURCE_AGE_S:-${CFG_TARGET_EVAL_DEPTH_MAX_SOURCE_AGE_S:-0.25}}
TARGET_EVAL_DEPTH_SAMPLE_GRID=${TARGET_EVAL_DEPTH_SAMPLE_GRID:-${CFG_TARGET_EVAL_DEPTH_SAMPLE_GRID:-5}}
TARGET_EVAL_DEPTH_MIN_VALID_SAMPLES=${TARGET_EVAL_DEPTH_MIN_VALID_SAMPLES:-${CFG_TARGET_EVAL_DEPTH_MIN_VALID_SAMPLES:-3}}
TARGET_EVAL_DEPTH_MIN_MATCHING_SAMPLES=${TARGET_EVAL_DEPTH_MIN_MATCHING_SAMPLES:-${CFG_TARGET_EVAL_DEPTH_MIN_MATCHING_SAMPLES:-2}}
TARGET_EVAL_DEPTH_ABS_TOLERANCE_M=${TARGET_EVAL_DEPTH_ABS_TOLERANCE_M:-${CFG_TARGET_EVAL_DEPTH_ABS_TOLERANCE_M:-0.12}}
TARGET_EVAL_DEPTH_RELATIVE_TOLERANCE=${TARGET_EVAL_DEPTH_RELATIVE_TOLERANCE:-${CFG_TARGET_EVAL_DEPTH_RELATIVE_TOLERANCE:-0.05}}
TARGET_EVAL_DETECTIONS_TOPIC=${TARGET_EVAL_DETECTIONS_TOPIC:-${CFG_TARGET_EVAL_DETECTIONS_TOPIC:-/lste/detections}}
TARGET_EVAL_TARGET_LABELS=${TARGET_EVAL_TARGET_LABELS:-${CFG_TARGET_EVAL_TARGET_LABELS:-}}
TARGET_EVAL_TARGET_CENTER_M=${TARGET_EVAL_TARGET_CENTER_M:-${CFG_TARGET_EVAL_TARGET_CENTER_M:-0,0,0}}
TARGET_EVAL_TARGET_SIZE_M=${TARGET_EVAL_TARGET_SIZE_M:-${CFG_TARGET_EVAL_TARGET_SIZE_M:-0.1,0.1,0.1}}
TARGET_EVAL_MIN_DEPTH_M=${TARGET_EVAL_MIN_DEPTH_M:-${CFG_TARGET_EVAL_MIN_DEPTH_M:-0.20}}
TARGET_EVAL_MAX_DEPTH_M=${TARGET_EVAL_MAX_DEPTH_M:-${CFG_TARGET_EVAL_MAX_DEPTH_M:-12.0}}
TARGET_EVAL_EDGE_MARGIN_PX=${TARGET_EVAL_EDGE_MARGIN_PX:-${CFG_TARGET_EVAL_EDGE_MARGIN_PX:-8}}
TARGET_EVAL_MAX_GAZEBO_STATE_AGE_S=${TARGET_EVAL_MAX_GAZEBO_STATE_AGE_S:-${CFG_TARGET_EVAL_MAX_GAZEBO_STATE_AGE_S:-0.50}}
TARGET_EVAL_EXPOSURE_HOLD_S=${TARGET_EVAL_EXPOSURE_HOLD_S:-${CFG_TARGET_EVAL_EXPOSURE_HOLD_S:-0.25}}
TARGET_EVAL_EPISODE_GAP_S=${TARGET_EVAL_EPISODE_GAP_S:-${CFG_TARGET_EVAL_EPISODE_GAP_S:-0.75}}
TARGET_EVAL_MIN_MATCH_IOU=${TARGET_EVAL_MIN_MATCH_IOU:-${CFG_TARGET_EVAL_MIN_MATCH_IOU:-0.10}}
TARGET_EVAL_MIN_SCORE=${TARGET_EVAL_MIN_SCORE:-${CFG_TARGET_EVAL_MIN_SCORE:-0.20}}

case "$DETECTOR" in
  groundingdino)
    DETECTOR_BACKEND=groundingdino
    ;;
  wedetect-base)
    DETECTOR_BACKEND=wedetect
    WDETECT_VARIANT=base
    WDETECT_CHECKPOINT="$WS/model/WeDetect/checkpoints/wedetect_base.pth"
    WDETECT_LANGUAGE_MODEL="$WS/model/WeDetect/xlm-roberta-base"
    WDETECT_VISION_ONNX="$WS/model/WeDetect/deploy/onnx_models/wedetect_base_vision.onnx"
    WDETECT_TRT_ENGINE_CACHE="$WS/model/WeDetect/deploy/trt_cache"
    WDETECT_RUNTIME=tensorrt
    ;;
  wedetect-large)
    DETECTOR_BACKEND=wedetect
    WDETECT_VARIANT=large
    WDETECT_CHECKPOINT="$WS/model/WeDetect/checkpoints/wedetect_large.pth"
    WDETECT_LANGUAGE_MODEL="$WS/model/WeDetect/xlm-roberta-large"
    WDETECT_VISION_ONNX="$WS/model/WeDetect/deploy/onnx_models/wedetect_large_vision.onnx"
    WDETECT_TRT_ENGINE_CACHE="$WS/model/WeDetect/deploy/trt_cache_large"
    WDETECT_RUNTIME=tensorrt
    ;;
  *)
    echo "[error] DETECTOR must be groundingdino, wedetect-base, or wedetect-large (got '$DETECTOR')" >&2
    exit 1
    ;;
esac

if [[ "$DETECTOR_BACKEND" == "wedetect" ]]; then
  DETECTOR_MIN_INTERVAL=$WDETECT_MIN_INTERVAL
  DETECTOR_INTERVAL_PASS=$WDETECT_INTERVAL_PASS
  DETECTOR_INTERVAL_SUSPICIOUS=$WDETECT_INTERVAL_SUSPICIOUS
  DETECTOR_INTERVAL_LOCKED=$WDETECT_INTERVAL_LOCKED
  DETECTOR_INTERVAL_EXHAUSTED=$WDETECT_INTERVAL_EXHAUSTED
  DETECTOR_NODE=lste_wedetect_det_node.py
  DETECTOR_ROS_NODE=/lste_det_node
  DETECTOR_MODEL_ARGS="_wedetect_source_dir:=$WDETECT_SOURCE_DIR \\
_wedetect_variant:=$WDETECT_VARIANT \\
_wedetect_checkpoint:=$WDETECT_CHECKPOINT \\
_wedetect_language_model:=$WDETECT_LANGUAGE_MODEL \\
_wedetect_score_threshold:=$WDETECT_SCORE_THRESHOLD \\
_wedetect_nms_iou:=$WDETECT_NMS_IOU \\
_wedetect_pre_nms_topk:=$WDETECT_PRE_NMS_TOPK \\
_wedetect_max_detections:=$WDETECT_MAX_DETECTIONS \\
_wedetect_use_fp16:=$WDETECT_USE_FP16 \\
_wedetect_runtime:=$WDETECT_RUNTIME \\
_wedetect_vision_onnx:=$WDETECT_VISION_ONNX \\
_wedetect_trt_engine_cache:=$WDETECT_TRT_ENGINE_CACHE \\
_wedetect_trt_max_classes:=$WDETECT_TRT_MAX_CLASSES \\
_wedetect_small_object_tile_search_enabled:=$WDETECT_SMALL_OBJECT_TILE_SEARCH_ENABLED \\
_wedetect_small_object_tile_layout:=$WDETECT_SMALL_OBJECT_TILE_LAYOUT \\
_wedetect_small_object_tile_grid:=$WDETECT_SMALL_OBJECT_TILE_GRID \\
_wedetect_small_object_tile_overlap:=$WDETECT_SMALL_OBJECT_TILE_OVERLAP \\
_wedetect_small_object_center_band_height_ratio:=$WDETECT_SMALL_OBJECT_CENTER_BAND_HEIGHT_RATIO \\
_wedetect_small_object_center_band_crops:=$WDETECT_SMALL_OBJECT_CENTER_BAND_CROPS \\
_wedetect_small_object_tile_interval:=$WDETECT_SMALL_OBJECT_TILE_INTERVAL"
else
  DETECTOR_MIN_INTERVAL=$DINO_MIN_INTERVAL
  DETECTOR_INTERVAL_PASS=$DINO_INTERVAL_PASS
  DETECTOR_INTERVAL_SUSPICIOUS=$DINO_INTERVAL_SUSPICIOUS
  DETECTOR_INTERVAL_LOCKED=$DINO_INTERVAL_LOCKED
  DETECTOR_INTERVAL_EXHAUSTED=$DINO_INTERVAL_EXHAUSTED
  DETECTOR_NODE=lste_det_node.py
  DETECTOR_ROS_NODE=/lste_det_node
  DETECTOR_MODEL_ARGS=""
fi
