#!/usr/bin/env bash
# Mission, prompt, state-machine, and visual-target configuration.
# This file is sourced by run_nodes_tmux.sh after CFG_* variables and
# _resolve() have been initialized.

TASK_JSON_VALUE=${TASK_JSON:-${CFG_TASK_JSON:-}}
TASK_ID=${TASK_ID:-${CFG_TASK_ID:-}}
if [[ -z "$TASK_JSON_VALUE" || -z "$TASK_ID" ]]; then
  echo "[error] TASK_JSON and TASK_ID must be set in $PIPELINE_CONFIG or the environment" >&2
  exit 1
fi
TASK_JSON=$(_resolve "$TASK_JSON_VALUE")
if [[ ! -f "$TASK_JSON" ]]; then
  echo "[error] TASK_JSON file not found: $TASK_JSON" >&2
  exit 1
fi

PRO3_SPAWN_X=${PRO3_SPAWN_X:-${CFG_PRO3_SPAWN_X:-0.0}}
PRO3_SPAWN_Y=${PRO3_SPAWN_Y:-${CFG_PRO3_SPAWN_Y:-0.0}}
PRO3_SPAWN_Z=${PRO3_SPAWN_Z:-${CFG_PRO3_SPAWN_Z:-0.0}}
PRO3_SPAWN_YAW=${PRO3_SPAWN_YAW:-${CFG_PRO3_SPAWN_YAW:-0.0}}
# Empty outside the benchmark so a production run cannot inherit its truth mask.
BENCHMARK_MANIFEST=${OFFICE_BUILDING_MANIFEST:-}
BENCHMARK_LEVEL=${OFFICE_BUILDING_LEVEL:-}
BENCHMARK_COLLISION_TRUTH_ENABLED=${OFFICE_BUILDING_COLLISION_TRUTH_ENABLED:-false}
BENCHMARK_CONTACT_SENSOR=${OFFICE_BUILDING_CONTACT_SENSOR:-false}
VLLM_URL=${VLLM_URL:-${CFG_VLLM_URL:-http://localhost:8000/v1}}
VLLM_MODEL=${VLLM_MODEL:-$(_resolve "${CFG_VLLM_MODEL:-model/MiniCPM/OpenBMB/MiniCPM4-0___5B}")}
PROMPT_CACHE_ENABLED=${PROMPT_CACHE_ENABLED:-${CFG_PROMPT_CACHE_ENABLED:-true}}
PROMPT_CACHE_DIR=${PROMPT_CACHE_DIR:-$(_resolve "${CFG_PROMPT_CACHE_DIR:-runtime/prompt_cache}")}
VLLM_START_TIMEOUT=${VLLM_START_TIMEOUT:-${CFG_VLLM_START_TIMEOUT:-240}}

ACCESS_TOPO_CONFIG=${ACCESS_TOPO_CONFIG:-$(_resolve "${CFG_ACCESS_TOPO_CONFIG:-src/lste_topo_access/topo_tree/cfgs/access_topo.yaml}")}
ACCESS_TOPO_CONFIG_PASS=${ACCESS_TOPO_CONFIG_PASS:-$(_resolve "${CFG_ACCESS_TOPO_CONFIG_PASS:-src/lste_topo_access/topo_tree/cfgs/access_topo_pass.yaml}")}
ACCESS_TOPO_CONFIG_SUS_C=${ACCESS_TOPO_CONFIG_SUS_C:-$(_resolve "${CFG_ACCESS_TOPO_CONFIG_SUS_C:-src/lste_topo_access/topo_tree/cfgs/access_topo_sus_c.yaml}")}
ACCESS_TOPO_TEST_NAME=${ACCESS_TOPO_TEST_NAME:-${CFG_ACCESS_TOPO_TEST_NAME:-default_test}}
ACCESS_TOPO_RUN_NAME=${ACCESS_TOPO_RUN_NAME:-${CFG_ACCESS_TOPO_RUN_NAME:-$ACCESS_TOPO_TEST_NAME}}
GP_FRONTIER_RVIZ=${GP_FRONTIER_RVIZ:-$(_resolve "${CFG_GP_FRONTIER_RVIZ:-src/lste_topo_access/launch/gp_frontier.rviz}")}
LEGACY_GP_FRONTIER_ENABLED=${LEGACY_GP_FRONTIER_ENABLED:-${CFG_LEGACY_GP_FRONTIER_ENABLED:-false}}

SUSPICIOUS_WINDOW=${SUSPICIOUS_WINDOW:-${CFG_SUSPICIOUS_WINDOW:-5}}
STATE_SUBTYPE_SWITCH_MIN_HITS=${STATE_SUBTYPE_SWITCH_MIN_HITS:-${CFG_STATE_SUBTYPE_SWITCH_MIN_HITS:-3}}
FOLLOW_LOCKED_DONE_TIME=${FOLLOW_LOCKED_DONE_TIME:-${CFG_FOLLOW_LOCKED_DONE_TIME:-4.0}}
TARGET_LOCK_TOTAL_MIN=${TARGET_LOCK_TOTAL_MIN:-${CFG_TARGET_LOCK_TOTAL_MIN:-0.60}}
TARGET_LOCK_SCORE_MIN=${TARGET_LOCK_SCORE_MIN:-${CFG_TARGET_LOCK_SCORE_MIN:-0.60}}
TARGET_LOCK_WINDOW=${TARGET_LOCK_WINDOW:-${CFG_TARGET_LOCK_WINDOW:-2}}
TARGET_LOCK_MIN_HITS=${TARGET_LOCK_MIN_HITS:-${CFG_TARGET_LOCK_MIN_HITS:-2}}
TARGET_LOCK_EXIT_TOTAL_MIN=${TARGET_LOCK_EXIT_TOTAL_MIN:-${CFG_TARGET_LOCK_EXIT_TOTAL_MIN:-0.60}}
TARGET_LOCK_EXIT_SCORE_MIN=${TARGET_LOCK_EXIT_SCORE_MIN:-${CFG_TARGET_LOCK_EXIT_SCORE_MIN:-0.60}}
TARGET_LOCK_EXIT_UNSTABLE_FRAMES=${TARGET_LOCK_EXIT_UNSTABLE_FRAMES:-${CFG_TARGET_LOCK_EXIT_UNSTABLE_FRAMES:-5}}

TARGET_DONE_MIN_BOX_WIDTH=${TARGET_DONE_MIN_BOX_WIDTH:-${CFG_TARGET_DONE_MIN_BOX_WIDTH:-0.06}}
TARGET_DONE_MIN_BOX_HEIGHT=${TARGET_DONE_MIN_BOX_HEIGHT:-${CFG_TARGET_DONE_MIN_BOX_HEIGHT:-0.06}}
TARGET_DONE_MIN_SCORE=${TARGET_DONE_MIN_SCORE:-${CFG_TARGET_DONE_MIN_SCORE:-0.40}}
TARGET_DONE_MIN_HOLD_TIME=${TARGET_DONE_MIN_HOLD_TIME:-${CFG_TARGET_DONE_MIN_HOLD_TIME:-0.30}}
TARGET_DONE_MIN_FRESH_HITS=${TARGET_DONE_MIN_FRESH_HITS:-${CFG_TARGET_DONE_MIN_FRESH_HITS:-3}}
TARGET_DONE_MAX_DETECTION_AGE=${TARGET_DONE_MAX_DETECTION_AGE:-${CFG_TARGET_DONE_MAX_DETECTION_AGE:-0.75}}
TARGET_FOLLOW_MIN_SCORE=${TARGET_FOLLOW_MIN_SCORE:-${CFG_TARGET_FOLLOW_MIN_SCORE:-0.20}}
TARGET_FOLLOW_MIN_BOX_SIZE=${TARGET_FOLLOW_MIN_BOX_SIZE:-${CFG_TARGET_FOLLOW_MIN_BOX_SIZE:-0.01}}
TARGET_FOLLOW_CANDIDATE_TIMEOUT=${TARGET_FOLLOW_CANDIDATE_TIMEOUT:-${CFG_TARGET_FOLLOW_CANDIDATE_TIMEOUT:-8.0}}
TARGET_FOLLOW_CONFIRM_HITS=${TARGET_FOLLOW_CONFIRM_HITS:-${CFG_TARGET_FOLLOW_CONFIRM_HITS:-2}}
TARGET_FOLLOW_CONFIRM_WINDOW=${TARGET_FOLLOW_CONFIRM_WINDOW:-${CFG_TARGET_FOLLOW_CONFIRM_WINDOW:-20.0}}
TARGET_FOLLOW_WEAK_CONFIRM_HITS=${TARGET_FOLLOW_WEAK_CONFIRM_HITS:-${CFG_TARGET_FOLLOW_WEAK_CONFIRM_HITS:-5}}
TARGET_FOLLOW_WEAK_MIN_AVERAGE_SCORE=${TARGET_FOLLOW_WEAK_MIN_AVERAGE_SCORE:-${CFG_TARGET_FOLLOW_WEAK_MIN_AVERAGE_SCORE:-0.24}}
TARGET_FOLLOW_SPATIAL_TOLERANCE=${TARGET_FOLLOW_SPATIAL_TOLERANCE:-${CFG_TARGET_FOLLOW_SPATIAL_TOLERANCE:-0.10}}
TARGET_OBSERVATION_HOLD=${TARGET_OBSERVATION_HOLD:-${CFG_TARGET_OBSERVATION_HOLD:-4.5}}
TARGET_DONE_REQUIRE_LOCKED=${TARGET_DONE_REQUIRE_LOCKED:-${CFG_TARGET_DONE_REQUIRE_LOCKED:-false}}
TARGET_DONE_REQUIRE_APPROACH_TERMINAL=${TARGET_DONE_REQUIRE_APPROACH_TERMINAL:-${CFG_TARGET_DONE_REQUIRE_APPROACH_TERMINAL:-false}}
DETECTION_MAX_SOURCE_IMAGE_AGE=${DETECTION_MAX_SOURCE_IMAGE_AGE:-${CFG_DETECTION_MAX_SOURCE_IMAGE_AGE:-1.0}}
FOLLOW_GOAL_PUBLISH_PERIOD=${FOLLOW_GOAL_PUBLISH_PERIOD:-${CFG_FOLLOW_GOAL_PUBLISH_PERIOD:-0.50}}
FOLLOW_TARGET_STEP_DISTANCE=${FOLLOW_TARGET_STEP_DISTANCE:-${CFG_FOLLOW_TARGET_STEP_DISTANCE:-1.5}}
FOLLOW_TARGET_USE_SCAN_CLIP=${FOLLOW_TARGET_USE_SCAN_CLIP:-${CFG_FOLLOW_TARGET_USE_SCAN_CLIP:-false}}
TARGET_APPROACH_STRATEGY=${TARGET_APPROACH_STRATEGY:-${CFG_TARGET_APPROACH_STRATEGY:-reachable_viewpoint_ladder}}
TARGET_BBOX_ALPHA=${TARGET_BBOX_ALPHA:-${CFG_TARGET_BBOX_ALPHA:-0.35}}
TARGET_HEADING_ALPHA=${TARGET_HEADING_ALPHA:-${CFG_TARGET_HEADING_ALPHA:-0.30}}
TARGET_MAX_HEADING_STEP_DEG=${TARGET_MAX_HEADING_STEP_DEG:-${CFG_TARGET_MAX_HEADING_STEP_DEG:-25.0}}
TARGET_GOAL_REACHED_RADIUS=${TARGET_GOAL_REACHED_RADIUS:-${CFG_TARGET_GOAL_REACHED_RADIUS:-0.75}}
TARGET_GOAL_HEADING_UPDATE_THRESHOLD_DEG=${TARGET_GOAL_HEADING_UPDATE_THRESHOLD_DEG:-${CFG_TARGET_GOAL_HEADING_UPDATE_THRESHOLD_DEG:-35.0}}
TARGET_CACHE_MAX_ADVANCES=${TARGET_CACHE_MAX_ADVANCES:-${CFG_TARGET_CACHE_MAX_ADVANCES:-2}}
TARGET_REACQUIRE_DURATION=${TARGET_REACQUIRE_DURATION:-${CFG_TARGET_REACQUIRE_DURATION:-6.0}}
TARGET_REACQUIRE_DISTANCE=${TARGET_REACQUIRE_DISTANCE:-${CFG_TARGET_REACQUIRE_DISTANCE:-1.0}}
TARGET_REACQUIRE_MAX_ATTEMPTS=${TARGET_REACQUIRE_MAX_ATTEMPTS:-${CFG_TARGET_REACQUIRE_MAX_ATTEMPTS:-1}}
FOLLOW_TARGET_LOST_TIMEOUT=${FOLLOW_TARGET_LOST_TIMEOUT:-${CFG_FOLLOW_TARGET_LOST_TIMEOUT:-12.0}}
FOLLOW_CONTEXT_STEP_DISTANCE=${FOLLOW_CONTEXT_STEP_DISTANCE:-${CFG_FOLLOW_CONTEXT_STEP_DISTANCE:-1.5}}
CONTEXT_GOAL_REACHED_RADIUS=${CONTEXT_GOAL_REACHED_RADIUS:-${CFG_CONTEXT_GOAL_REACHED_RADIUS:-0.55}}
CONTEXT_GOAL_HEADING_UPDATE_THRESHOLD_DEG=${CONTEXT_GOAL_HEADING_UPDATE_THRESHOLD_DEG:-${CFG_CONTEXT_GOAL_HEADING_UPDATE_THRESHOLD_DEG:-35.0}}
CONTEXT_FOLLOW_COOLDOWN=${CONTEXT_FOLLOW_COOLDOWN:-${CFG_CONTEXT_FOLLOW_COOLDOWN:-30.0}}
CONTEXT_STATE_HOLD_TIME=${CONTEXT_STATE_HOLD_TIME:-${CFG_CONTEXT_STATE_HOLD_TIME:-4.0}}
